export const postsActionTypes = {
    FETCHPOSTS: 'FETCH_POSTS',
    FETCHPOSTSSUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCHPOSTSFAILURE: 'FETCH_POSTS_FAILURE',

    FETCHACTIVITIES: 'FETCH_ACTIVITIES',
    FETCHACTIVITIESSUCCESS: 'FETCH_ACTIVITIES_SUCCESS',
    FETCHACTIVITIESFAILURE: 'FETCH_ACTIVITIES_FAILURE',
}
