export const userActionTypes = {
    FETCHUSER: 'FETCH_USER',
    FETCHUSERSUCCESS: 'FETCH_USER_SUCCESS',
    FETCHUSERFAILURE: 'FETCH_USER_FAILURE',

    EDITUSERPROFILE: 'EDIT_USER_PROFILE',


    UPDATEUSERPROFILE: 'UPDATE_USER_PROFILE',


}
