export const userActionTypes = {
    FETCHUSER: 'FETCH_USER',
    FETCHUSERSUCCESS: 'FETCH_USER_SUCCESS',
    FETCHUSERFAILURE: 'FETCH_USER_FAILURE',

    FETCHFOLLOWINGS: 'FETCH_FOLLOWINGS',
    FETCHFOLLOWINGSSUCCESS: 'FETCH_FOLLOWINGS_SUCCESS',
    FETCHFOLLOWINGSFAILURE: 'FETCH_FOLLOWINGS_FAILURE',

    FETCHFOLLOWERS: 'FETCH_FOLLOWERS',
    FETCHFOLLOWERSSUCCESS: 'FETCH_FOLLOWERS_SUCCESS',
    FETCHFOLLOWERSFAILURE: 'FETCH_FOLLOWERS_FAILURE',

    FOLLOW: 'FOLLOW',
    FOLLOWSUCCESS: 'FOLLOW_SUCCESS',
    FOLLOWFAILURE: 'FOLLOW_FAILURE',

    UNFOLLOW: 'UNFOLLOW',
    UNFOLLOWSUCCESS: 'UNFOLLOW_SUCCESS',
    UNUNFOLLOWFAILURE: 'UNFOLLOW_FAILURE',


    EDITUSERPROFILE: 'EDIT_USER_PROFILE',


    UPDATEUSERPROFILE: 'UPDATE_USER_PROFILE',


}
