export const postActionTypes = {
    FETCHPOST: 'FETCH_POST',
    FETCHPOSTSUCCESS: 'FETCH_POST_SUCCESS',
    FETCHPOSTFAILURE: 'FETCH_POST_FAILURE',

    ADDPOST: 'ADD_POST',
    ADDPOSTSUCCESS: 'ADD_POST_SUCCESS',
    ADDPOSTFAILURE: 'ADD_POST_FAILURE',

    UPDATEPOST: 'UPDATE_POST',
    UPDATEPOSTSUCCESS: 'UPDATE_POST_SUCCESS',
    UPDATEPOSTFAILURE: 'UPDATE_POST_FAILURE',

    DELETEPOST: 'DELETE_POST',
    DELETEPOSTSUCCESS: 'DELETE_POST_SUCCESS',
    DELETEPOSTFAILURE: 'DELETE_POST_FAILURE',

    CLEARCURRENTPOST: 'CLEAR_CURRENT_POST',
}
